### PR TITLE
Feature 5943877783 tinypng key and dsstore file removal

### PR DESCRIPTION
**Pull request by RyanCrux**
## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
    Added repo secret for the compress workflow.
    removed the .DS_Store file 
    Added .DS_Store to the .gitignore file in any directory

## Related Tickets & Documents
- Monday Task #5943877783

## QA Instructions, Screenshots, Recordings

-see exclude for ds_store file in gitignore
-see tinypng api key added to compress.yml

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized

## Changed Files in this Pull Request ##
- .github/workflows/compress.yml
 - .gitignore

### CODE REVIEW

**Review by will-bbg — CHANGES_REQUESTED** [review]
Update secrets variable

**Review by will-bbg — APPROVED** [review]
👍🏽

**Comment by RyanCrux** [comment]
After my PR is approved, do you want the reviewer (you) or the creator (me) to merge?

**Comment by will-bbg** [comment]
You as the creator merges into `main`

**Pull request merged**
