### PR TITLE
rp-modal-move-js-element-checks

### PR DESCRIPTION
**Pull request by ronald-bbg**
Hi @ecstech-admin / @will-bbg  -

I made the following changes:

1) Moved modal code to footer.html and footer-sub.html
2) Removed all references to hide #smDiv5 for the header nav (doesn't exist)
3) Added check for magnific popup function call
4) Added check for lazy function call
5) Fixed header nav links
6) Added USWDS top header dropdown up and down arrows for desktop and mobile
7) Added sub-page for testing purposes

Once approved and merged to main here, looking to apply to NCCHI, DOE, and Fellowships...

### CODE REVIEW

**Review by will-bbg — CHANGES_REQUESTED** [review]
This all looks good. I did run Lighthouse via DevTools in Chrome. Looks like there are broken links to svgs and font files. Please investigate.
Screenshot 2023-12-20 at 3 29 58 PM

**Comment by will-bbg** [comment]
^^ Don't mind what I did there

**Comment by ronald-bbg** [comment]
@will-bbg / @ecstech-admin I'm going to add the fellowship and DOE url fixes here as well - commit coming...

**Comment by ronald-bbg** [comment]
As a byproduct of fixing the arrow file references, top header "Here's how you know" **dropdown arrow** was added.

USWDS:
Screenshot 2023-12-21 at 12 10 06 PM

This PR:
Screenshot 2023-12-21 at 12 11 54 PM

**Review by ecstech-admin — CHANGES_REQUESTED** [review]
Add closing head tag to both index.html and sub-page/index.html
Add "[VA Intrapreneurial Product Marketplace](/ecosystem/views/innovators-network/vaipm.html)" to nav (last item in iNet under "Employee Innovator Fundamentals")
Rm "subpage" dir and index.html from _site
Make sub-page header content/layout same as index.html: currently using NCCHI content

**Comment by ronald-bbg** [comment]
@ecstech-admin / @will-bbg Requesting re-review for dropdown arrow fixes using package usa-media-block on usa-banner and hide for usa-header (main nav)

**Review by will-bbg — CHANGES_REQUESTED** [review]
Icons - are the additional `expand_less.svg` and `expand_more.svg` necessary now that we added the media-block package? If not, please remove. If they are necessary, still remove and use the icons already in the `uswds/img/usa-icons/` directory

USWDS Theme Custom Styles - please do not place any styling in this file, as it is good SASS practice to group css in separate files. Any USWDS navigation overrides need to be placed in this specific file,` /sass/vha/components/navigation/_index.scss`. While you are in there, please clean up the css and turn into proper SASS syntax

**Comment by ronald-bbg** [comment]
It looks like we need to modify the file path in icon.scss that comes from USWDS components:

mask-image: url("#{$path}/usa-icons/#{$filename-base}.svg"),

I'll see if we can edit this file without an override...more to come...

**Review by ecstech-admin — CHANGES_REQUESTED** [review]
rm duplicate icons from _site like you did in assets

_site/assets/img/icons/usa-icons

**Comment by ronald-bbg** [comment]
this is ready for approval

**Review by ecstech-admin — APPROVED** [review]
Looks great! Good to go.

**Review by will-bbg — APPROVED** [review]

**Pull request merged**
